# Generated by Django 3.0.7 on 2020-07-16 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisaAgencyProspect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('unsubscribe', models.BooleanField(default=False)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.City')),
            ],
        ),
        migrations.CreateModel(
            name='VisaAgencyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('active', models.BooleanField(default=True)),
                ('description', models.TextField()),
                ('website_url', models.TextField(blank=True, null=True)),
                ('facebook', models.TextField(blank=True, null=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='subscription.Subscription')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('contact', models.TextField(default='')),
                ('geo_lat', models.TextField(blank=True, null=True)),
                ('geo_lon', models.TextField(blank=True, null=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visa_agency.VisaAgencyModel')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.City')),
            ],
        ),
        migrations.CreateModel(
            name='AgencyUserNoteModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('content', models.TextField()),
                ('is_visible', models.BooleanField(default=True)),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='visa_agency.VisaAgencyModel')),
            ],
            options={
                'ordering': ('date',),
            },
        ),
        migrations.CreateModel(
            name='AgencyService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(blank=True, null=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visa_agency.VisaAgencyModel')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Service')),
            ],
        ),
    ]
