# Generated by Django 3.0.7 on 2020-07-17 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa_agency', '0002_auto_20200716_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='visaagencyprospect',
            name='mails',
            field=models.IntegerField(default=0),
        ),
    ]
