# Generated by Django 3.0.7 on 2020-07-16 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('visa_agency', '0001_initial'),
        ('expat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visaquoteresponsemodel',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='visa_agency.VisaAgencyModel'),
        ),
        migrations.AddField(
            model_name='visaquoteresponsemodel',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expat.VisaQuoteRequestModel'),
        ),
        migrations.AddField(
            model_name='visaquoterequestmodel',
            name='expat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='expat.ExpatModel'),
        ),
        migrations.AddField(
            model_name='visaquoterequestmodel',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Service'),
        ),
        migrations.AddField(
            model_name='visaquoterequestmodel',
            name='visa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='expat.VisaModel'),
        ),
        migrations.AddField(
            model_name='visamodel',
            name='expat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expat.ExpatModel'),
        ),
        migrations.AddField(
            model_name='expatmodel',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.City'),
        ),
        migrations.AddField(
            model_name='expatmodel',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
