# Generated by Django 3.0.7 on 2020-07-16 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expat', '0003_auto_20200716_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expatmodel',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='visamodel',
            name='entry_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='visamodel',
            name='expiration',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='visamodel',
            name='issue_date',
            field=models.DateField(),
        ),
    ]
