# Generated by Django 3.0.7 on 2020-07-16 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('idx', models.CharField(db_index=True, max_length=8, unique=True)),
                ('type', models.CharField(choices=[('LL', 'Leads Limited'), ('DL', 'Date Limited')], default='LL', max_length=2)),
                ('price', models.FloatField(blank=True, null=True)),
                ('description', models.TextField()),
                ('leads', models.IntegerField(blank=True, null=True)),
                ('duration', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('leads', models.IntegerField()),
                ('status', models.CharField(choices=[('A', 'Active'), ('E', 'Expired'), ('P', 'Pending')], default='P', max_length=2)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='subscription.SubscriptionType')),
            ],
        ),
    ]
